canonical: https://gematik.de/fhir/isik/v2/Medikation
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
status: active
version: 2.0.3
dependencies:
  de.medizininformatikinitiative.kerndatensatz.medikation: 1.0.10
  hl7.fhir.r4.core: 4.0.1
  de.gematik.isik-basismodul: 2.0.x
